plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle' version '[7.0.3,8)'
    id 'idea'
}
base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}
//mixin {
//    config("${mod_id}.mixins.json")
//    config("${mod_id}.forge.mixins.json")
//
//    config("${mod_id}.accessories.mixins.json")
//    config("${mod_id}.alexmobs.mixins.json")
//    config("${mod_id}.bedrockify.mixins.json")
//    config("${mod_id}.blur.mixins.json")
//    config("${mod_id}.cataclysm.mixins.json")
//    config("${mod_id}.dynamicfps.mixins.json")
//    config("${mod_id}.elementa.mixins.json")
//    config("${mod_id}.emf.mixins.json")
//    config("${mod_id}.epicfight.mixins.json")
//    config("${mod_id}.iris.mixins.json")
//    config("${mod_id}.mca.mixins.json")
//    config("${mod_id}.optifine.mixins.json")
//    config("${mod_id}.rei.mixins.json")
//    config("${mod_id}.resolutioncontrol.mixins.json")
//    config("${mod_id}.sereneseasons.mixins.json")
//    config("${mod_id}.sodium.mixins.json")
//    config("${mod_id}.voxy.mixins.json")
//    config("${mod_id}.xaerosmimimap.mixins.json")
//    config("${mod_id}.xaerosworldmap.mixins.json")
//}
jar {
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    // Automatically enable forge AccessTransformers if the file exists
    // This location is hardcoded in Forge and can not be changed.
    // https://github.com/MinecraftForge/MinecraftForge/blob/be1698bb1554f9c8fa2f58e32b9ab70bc4385e60/fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L123
    // Forge still uses SRG names during compile time, so we cannot use the common AT's
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = true
        accessTransformer = at
    }

    runs {
        configureEach {
            args "-mixin.config=${mod_id}.mixins.json"
            args "-mixin.config=${mod_id}.forge.mixins.json"
        }
        client {
            workingDir = file('runs/client')
        }

        server {
            workingDir = file('runs/server')
        }

        data {
            workingDir = file('runs/data')
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    maven minecraft.mavenizer
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    compileOnly project(':stubs')
}

publishing {
    publications {
        mavenJava(MavenPublication) {

        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}
