plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.4.1'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.4.1'

    compileOnly("org.ow2.asm:asm:9.9")
    compileOnly("org.ow2.asm:asm-tree:9.9")
    compileOnly("org.ow2.asm:asm-analysis:9.9")
    compileOnly("org.ow2.asm:asm-commons:9.9")
    compileOnly("org.ow2.asm:asm-util:9.9")

    compileOnly project(':stubs')

    implementation("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}") { transitive = false }
    implementation("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-linux") { transitive = false }
    implementation("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-macos") { transitive = false }
    implementation("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-windows") { transitive = false }

    // for OSC tracker support
    implementation("com.illposed.osc:javaosc-core:0.9")

    // bHaptics Integration
    implementation("com.github.bhaptics:tact-java:0.1.4")

    // needed dependencies
    compileOnly("com.google.code.findbugs:jsr305:3.0.2")
    compileOnly('com.electronwill.night-config:toml:3.6.6')

    implementation("com.illposed.osc:javaosc-core:0.9")
    implementation("com.github.bhaptics:tact-java:0.1.4")
    implementation("org.java-websocket:Java-WebSocket:1.5.1")

    //LaunchPopup
    implementation 'com.github.Vivecraft:LaunchPopup:1.1.1'

    // for sodium compat
    compileOnly "maven.modrinth:sodium:mc1.21.11-0.8.2-fabric"

    // for iris compat
    compileOnly "maven.modrinth:iris:1.10.4+1.21.11-fabric"

    // for REI compat
    compileOnly("me.shedaniel:RoughlyEnoughItems-fabric:18.0.796") { exclude group: "net.fabricmc" exclude group: "net.fabricmc.fabric-api" exclude group: "dev.architectury" }

    // for Pehkui compat
    compileOnly("com.github.Virtuoel:Pehkui:3.7.12") { exclude group: "net.fabricmc" exclude group: "net.fabricmc.fabric-api" }

    // other mods
    compileOnly "maven.modrinth:dynamic-fps:3.4.3"
    // modCompileOnly("com.simibubi.create:create-fabric-1.19.2:0.5.0.i-969+1.19.2")
    // modCompileOnly "maven.modrinth:lithium:mc1.20.4-0.12.1"
    // modCompileOnly "maven.modrinth:indium:1.0.30+mc1.20.4"
    compileOnly "maven.modrinth:resolution-control-plus:3.0.0"

    // for immersive portals compat
    compileOnly('com.github.iPortalTeam:ImmersivePortalsMod:v5.1.7-mc1.20.4') { exclude group: "net.fabricmc" exclude group: "net.fabricmc.fabric-api" }

    //for epic fight compat
    compileOnly("maven.modrinth:epic-fight:20.6.3")
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}
