plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        data {
            clientData()

            // DataGen can be run by - "./gradlew :neoforge:runData" in Terminal.
            // Specify the modid for data generation, where to output the resulting resource, and where to look for existing resources.
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

configurations.all {
    resolutionStrategy.eachDependency { details ->
        if (details.requested.group == "org.lwjgl" &&
            details.requested.name != "lwjgl-openvr") {
            details.useVersion "3.4.1"
        }
    }
}

dependencies {
    implementation("org.lwjgl:lwjgl:3.4.1")
    implementation("org.lwjgl:lwjgl-opengl:3.4.1")
    implementation("org.lwjgl:lwjgl:3.4.0:natives-windows")
    implementation("org.lwjgl:lwjgl-opengl:3.4.0:natives-windows")
    implementation("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}") { transitive = false }
    implementation("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-linux") { transitive = false }
    implementation("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-macos") { transitive = false }
    implementation("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-windows") { transitive = false }
    implementation("com.illposed.osc:javaosc-core:0.9") { transitive = false }
    implementation("com.github.bhaptics:tact-java:0.1.4") { transitive = false }
    implementation("org.java-websocket:Java-WebSocket:1.5.1") { transitive = false }

    compileOnly project(':stubs')

    // shadow the natives
    jarJar("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}") { transitive = false }
    jarJar("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-linux") { transitive = false }
    jarJar("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-macos") { transitive = false }
    jarJar("org.lwjgl:lwjgl-openvr:${rootProject.lwjgl_version}:natives-windows") { transitive = false }

    jarJar(implementation("com.illposed.osc:javaosc-core:0.9"))
    jarJar(implementation("com.github.bhaptics:tact-java:0.1.4"))
    jarJar(implementation("org.java-websocket:Java-WebSocket:1.5.1"))

    // for sodium compat
    compileOnly "maven.modrinth:sodium:mc1.21.11-0.8.2-fabric"

    // for iris compat
    compileOnly "maven.modrinth:iris:1.10.4+1.21.11-fabric"

    // for REI compat
    compileOnly("me.shedaniel:RoughlyEnoughItems-fabric:18.0.796") { exclude group: "net.fabricmc" exclude group: "net.fabricmc.fabric-api" exclude group: "dev.architectury" }

    // for Pehkui compat
    compileOnly("com.github.Virtuoel:Pehkui:3.7.12") { exclude group: "net.fabricmc" exclude group: "net.fabricmc.fabric-api" }

    // other mods
    compileOnly "maven.modrinth:dynamic-fps:3.4.3"
    // modCompileOnly("com.simibubi.create:create-fabric-1.19.2:0.5.0.i-969+1.19.2")
    // modCompileOnly "maven.modrinth:lithium:mc1.20.4-0.12.1"
    // modCompileOnly "maven.modrinth:indium:1.0.30+mc1.20.4"
    compileOnly "maven.modrinth:resolution-control-plus:3.0.0"

    // for immersive portals compat
    compileOnly('com.github.iPortalTeam:ImmersivePortalsMod:v5.1.7-mc1.20.4') { exclude group: "net.fabricmc" exclude group: "net.fabricmc.fabric-api" }

    //for epic fight compat
    compileOnly("maven.modrinth:epic-fight:20.6.3")
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName, it.getTaskName(null, 'jarJar')].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'neoforge')
            }
        }
    }
}
